name: ci

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: pip install mkdocs-material
      - run: python generate.py ${{ secrets.YT_API_KEY }}
      - run: mkdocs gh-deploy --force
  