name: deploy

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install --git https://github.com/clitic/trending-music
      - run: /home/runner/.cargo/bin/trending_music
      - run: ls
