name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  YT_API_KEY: ${{ secrets.YT_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Create or switch to gh-pages branch
        run: |
          if git ls-remote --exit-code --heads origin gh-pages; then
            echo "Branch exists, checking out..."
            git switch gh-pages
          else
            echo "Branch does not exist, creating..."
            git checkout -b gh-pages
            rm -r .github .gitignore src Cargo.toml
          fi
      - name: Commit and push changes to gh-pages
        run: |
          git add -A
          git commit -am "updated data.json"
          git push origin gh-pages
