name: deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  YT_API_KEY: ${{ secrets.YT_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Create and switch to gh-pages branch
        run: git checkout -b gh-pages
      - name: Generate data
        run: |
          cargo install --git https://github.com/clitic/trending-music
          /home/runner/.cargo/bin/trending_music
      - name: Push changes to gh-pages
        run: |
          git push origin gh-pages
