name: tests

on:
  push:
    branches: ["mains"]
  pull_request:
    branches: ["mains"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Tests
      run: cargo test
